server:
  port: 8082

spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest

      exchange:
        producer: ex.producer
      routing-key:
        producer: rk.producer
      deadletter:
        producer: dlq.producer


